import React from "react";
import Head from "next/head";
import OpenAILoginContent from "@/components/login/OpenAILoginContent";

const Login = () => {
  return (
    <>
      <Head>
        <title>AI Projects - Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/favicon.png" />
      </Head>
      <OpenAILoginContent />
    </>
  );
};

export default Login;
